In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


#https://www.learnpytorch.io/


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


#tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][2]

tensor([2, 4, 5])

In [ ]:
#Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1787, 0.7520, 0.1897, 0.5879],
        [0.2437, 0.7534, 0.7511, 0.8280],
        [0.2333, 0.5747, 0.6970, 0.4556]])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour, height, width (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of al ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# Creating a range of tensor
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.,6.,9.],
                                dtype=None,
                                device=None,
                                requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# zeros @ ones error : mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)
zeros * ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Getting information from tensors

1. Tensors not right datatype -to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape -to do get shape from a tensor, can use `tensor.shape`
3. Tensors not right device -to do get device from a tensor, can use `tensor.device`


In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0931, 0.4061, 0.7394, 0.7752],
        [0.8931, 0.9616, 0.3348, 0.0605],
        [0.9530, 0.8869, 0.7276, 0.5572]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0931, 0.4061, 0.7394, 0.7752],
        [0.8931, 0.9616, 0.3348, 0.0605],
        [0.9530, 0.8869, 0.7276, 0.5572]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating tensors

Tensor Operations :
add
sub
mul
div
matrix mul

In [ ]:
# create tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
# Element-wise matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4]])
tensor_B = torch.tensor([[5,6],[7,8]])
tensor_A * tensor_B

tensor([[ 5, 12],
        [21, 32]])

In [ ]:
# # Element-wise matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[7,8]])
tensor_B = torch.tensor([[5,6],[7,8]])
tensor_A * tensor_B # Error : The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [ ]:
tensor_A = torch.tensor([[1,2],[3,4]])
tensor_B = torch.tensor([[5,6],[7,7]])

In [ ]:

print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [ ]:
# Create 2 matrix and compute matrix multipilcation
tensor_c = tensor_A @ tensor_B
print(tensor_c)
print(tensor_c.shape)

tensor([[19, 20],
        [43, 46]])
torch.Size([2, 2])


In [ ]:
torch.matmul(tensor_A,tensor_B)

tensor([[19, 20],
        [43, 46]])

In [ ]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[5,6],[7,7],[9,4]])

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[5, 7, 9],
         [6, 7, 4]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[17, 21, 17],
        [39, 49, 43],
        [61, 77, 69]])

# Finding the min, max, mean, sum


In [ ]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
torch.mean(x) #could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [ ]:
# Finding the position of the min and max
x.argmin(), x.argmax()

(tensor(0), tensor(9))

# Reshaping, Viewing, and Stack

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of cretain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (`vstack`) or side by side (`hstack`)
* Squeez - remove all `1` dimension from a tensor
* Unsqueez - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way


In [ ]:
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes the x as x and z shares the same memiry
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_original = torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [ ]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
x_original[0,0,0] = 12

In [ ]:
x_permuted[0,0,0]

tensor(12.)

# indexing
Indexing with pytorch is similar to indexing in numpy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][1:2]

tensor([[4, 5, 6]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x
x[:,:,2]

tensor([[3, 6, 9]])

# PyTorch tensors and NumPy

In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # waring numpy -> pytorch default dtype - float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility  (trying to take random out of random)
* To reduce the randomness in nn and pytorch comes the concept of a `random seed`

In [ ]:
random_a = torch.rand(3,4)
random_b = torch.rand(3,4)
print(random_a)
print(random_b)
print(random_a == random_b)

tensor([[0.1521, 0.7747, 0.2309, 0.5506],
        [0.3389, 0.7849, 0.2726, 0.6813],
        [0.4222, 0.8770, 0.3493, 0.9564]])
tensor([[0.1166, 0.0471, 0.4762, 0.9848],
        [0.6553, 0.4386, 0.8609, 0.1761],
        [0.6687, 0.0406, 0.7576, 0.1801]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# set the random seed
Random_seed = 42

torch.manual_seed(Random_seed)
random_c = torch.rand(3,4)

torch.manual_seed(Random_seed)
random_d = torch.rand(3,4)

print(random_c)
print(random_d)
print(random_c == random_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on the GPUs

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# tensors back to the CPU
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')